// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBLOcomPzjJzpyP1AGbkGCwKxZ12JMQcQ',
    appId: '1:593119351285:web:13e93bc1c86c6d13f110bc',
    messagingSenderId: '593119351285',
    projectId: 'api-flutter-3a397',
    authDomain: 'api-flutter-3a397.firebaseapp.com',
    databaseURL: 'https://api-flutter-3a397-default-rtdb.firebaseio.com',
    storageBucket: 'api-flutter-3a397.appspot.com',
    measurementId: 'G-5WKSWKP402',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2o3UFKFP4MZslY_JEeplAqL1ZVXqnctk',
    appId: '1:593119351285:android:919fd1dd67db9717f110bc',
    messagingSenderId: '593119351285',
    projectId: 'api-flutter-3a397',
    databaseURL: 'https://api-flutter-3a397-default-rtdb.firebaseio.com',
    storageBucket: 'api-flutter-3a397.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATLjUlSS5AKSCZ53vL_0pQJZt4DSWjCjM',
    appId: '1:593119351285:ios:c18be4d4cf351beaf110bc',
    messagingSenderId: '593119351285',
    projectId: 'api-flutter-3a397',
    databaseURL: 'https://api-flutter-3a397-default-rtdb.firebaseio.com',
    storageBucket: 'api-flutter-3a397.appspot.com',
    iosClientId: '593119351285-c99lrmib4pgrn3dj15s8bpseqph2ujtt.apps.googleusercontent.com',
    iosBundleId: 'com.example.petSociety',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATLjUlSS5AKSCZ53vL_0pQJZt4DSWjCjM',
    appId: '1:593119351285:ios:c18be4d4cf351beaf110bc',
    messagingSenderId: '593119351285',
    projectId: 'api-flutter-3a397',
    databaseURL: 'https://api-flutter-3a397-default-rtdb.firebaseio.com',
    storageBucket: 'api-flutter-3a397.appspot.com',
    iosClientId: '593119351285-c99lrmib4pgrn3dj15s8bpseqph2ujtt.apps.googleusercontent.com',
    iosBundleId: 'com.example.petSociety',
  );
}
